const wordListName = 'P1 Dictation 1';

const wordList = [
  "Good", 
  "morning", 
  "afternoon", 
  "Goodbye", 
  "a", 
  "principal", 
  "teacher", 
  "monitor", 
  "classmate", 
  "What", 
  "is", 
  "your", 
  "name", 
  "My", 
  "Fred", 
  "Can", 
  "you", 
  "spell", 
  "please", 
  "How", 
  "old", 
  "are", 
  "I", 
  "am", 
  "six", 
  "years", 
  "five", 
  "seven", 
  "Hello", 
  "Hi", 
  "Lucy", 
  "James", 
  "Ivy", 
  "Evan", 
  "friends"
];

const sentenceList = [
  "Good morning.", 
  "Good afternoon.", 
  "Goodbye.", 
  "a principal", 
  "a teacher", 
  "a monitor", 
  "a classmate", 
  "What is your name?", 
  "My name is Fred.", 
  "Can you spell your name, please?", 
  "How old are you?", 
  "I am six years old.", 
  "five", 
  "six", 
  "seven", 
  "Hello!", 
  "Hi!", 
  "How are you?", 
  "Lucy", 
  "James", 
  "Ivy", 
  "Evan", 
  "friends", 
]

function computeQuestionFromIndexAndWord(currentIndex, currentWord) {
  return null;
}